onlyBuiltDependencies:
  - esbuild
  - sharp
verifyDepsBeforeRun: false
minimumReleaseAgeExclude:
  - astro@6.3.6
  - '@astrojs/markdown-satteri@0.3.1'
  - astro@7.0.0
allowBuilds:
  esbuild: set this to true or false
  sharp: set this to true or false
